export const mutationKey = {
  DELETE_MY_WORKOUT: "DELETE_MY_WORKOUT",
  POST_MAKE_ROUTINE: "POST_MAKE_ROUTINE",
  POST_ADD_ROUTINE: "POST_ADD_ROUTINE",
  POST_EDIT_PASSWORD: "POST_EDIT_PASSWORD",
  POST_RECOMMEND: "POST_RECOMMEND",
  POST_RECOMMENDID: "POST_RECOMMENDID",
  POST_SIGNUP: "POST_SIGNUP",
  POST_LOGOUT: "POST_LOGOUT",
  POST_LOGIN: "POST_LOGIN",
  POST_EDIT_WORKOUT_LIST: "POST_EDIT_WORKOUT_LIST",
  POST_EDIT_PROFILE: "POST_EDIT_PROFILE",
}
