export const queryKey = {
  GET_FETCH_RECENT_BODYDATA: "GET_FETCH_RECENT_BODYDATA",
  GET_BODYPART: "GET_BODYPART",
  GET_MACHINE_LIST: "GET_MACHINE_LIST",
  GET_WORKOUT_BATCH: "GET_WORKOUT_BATCH",
  GET_USERINFO: "GET_USERINFO",
  GET_WORKOUT: "GET_WORKOUT",
  GET_ROUTINE: "GET_ROUTINE",
  GET_MY_WORKOUT: "GET_MY_WORKOUT",
  GET_MY_ROUTINES: "GET_MY_ROUTINES",
}
