interface Props {
  ftsize: string
  ftcolor: string
  ftweight: string
  isSelected: boolean
  $isSelected: boolean
  warnBudget: string
  showShadow: boolean
  isover: boolean
  isFocused: boolean
  name: string
  valueHistory: string
  isValidState: any
  $isValid: boolean
  isReady: boolean
  backcolor: string
  fontcolor: string
  $isChecked: boolean
  $isError: boolean
  $isDirty: boolean
  flex: any
  status: any
  sex: string
  $status: number
  isClicked: boolean
  $isLoginModal: boolean
  $isCancleModal: boolean
  $isRecommend: boolean
}
